export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_ISSUE = 'CREATE_ISSUE';
export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUE = 'FETCH_ISSUE';
export const DELETE_ISSUE = 'DELETE_ISSUE';
export const EDIT_ISSUE = 'EDIT_ISSUE';
export const COUNT = 'COUNT';

export const CREATE_PROJECT = 'CREATE_PROJECT';
export const FETCH_PROJECTS = 'FETCH_PROJECTS';
export const FETCH_PROJECT = 'FETCH_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const EDIT_PROJECT = 'EDIT_PROJECT';

export const SELECTED_PROJECT = 'SELECTED_PROJECT';
export const SELECTED_ISSUE = 'SELECTED_ISSUE';

export const CREATE_USER = 'CREATE_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USER = 'FETCH_USER';
export const DELETE_USER = 'DELETE_USER';
export const EDIT_USER = 'EDIT_USER';

export const ADD_PROJECTUSER = 'ADD_PROJECTUSER';
export const FETCH_PROJECTUSERS = 'FETCH_PROJECTUSERS';
export const DELETE_PROJECTUSER = 'DELETE_PROJECTUSER';

export const CREATE_COMMENT = 'CREATE_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';

export const SET_NAVBAR = 'SET_NAVBAR';
